Allow click-dragging to select in the priority list
frzyc/genshin-optimizer pull request #1035
Opened 2023-02-25 17:56 UTC by nguyentvan7

![chrome_wldx7G8zNh](https://user-images.githubusercontent.com/36019388/221372277-c7eac9b3-52a8-465c-bf89-6d2f396f0dcc.gif)

2023-02-25 21:37 UTC, frzyc commented
Even in your demo this messed with tooltips. The issue is that when you hold onto any particular icon, it will trigger the delayed tooltip hover. you might need to find a way to disable the tooltip when it is registering a hold.
Does this toggle or does each drag only allow/disallow?

2023-02-26 06:18 UTC, nguyentvan7 commented
the drag will toggle everything you dragged over. The second drag of the example shows that a bit

2023-02-28 05:46 UTC, nguyentvan7 commented
I added disabling the tooltip. You can also try commit 1eb12ca, as adjusting the timing makes it a lot better. If the user is taking more than 0.5s to click-drag out of the current character, feels like theyre a bit slow, but I will leave it up to you

2023-03-01 00:20 UTC, frzyc commented on apps/frontend/src/app/Components/Character/CharacterCardPico.tsx
> -    <BootstrapTooltip placement="top" title={
this variant should have no deplay, since its just a simple name tooltip that goes in the main tooltip

2023-03-01 00:28 UTC, frzyc requested changes
<img width="663" alt="image" src="https://user-images.githubusercontent.com/1754901/222014146-e6729c3a-d10a-4c19-a6e5-e1e90e199a39.png">

2023-03-05 08:35 UTC, nguyentvan7 commented
I wonder if being able to toggle everything is too complex. Like if the user starts a drag on an excluded character, should that drag only select excluded characters until they finish?

2023-03-06 21:46 UTC, nguyentvan7 commented
Refer to https://github.com/frzyc/genshin-optimizer/pull/1068

2023-03-06 21:46 UTC, closed without merging