Fix item descriptions
frzyc/genshin-optimizer pull request #1161
Opened 2023-04-24 20:35 UTC by vapopescu

Fixes #273
These changes instruct the pipeline to substitute '\n' to '<br/>' in the weapon and material descriptions. Also fixed some code-duplication in 'WeaponSheet.tsx'

Resulting Changes:
- 'Dodoco Tales' has correct item description
- 'Sword of Descension' and 'Predator' (PSN Traveler and Aloy weapons) have correct passive description
- Material descriptions are HTML-safe, for future-proofing

![image](https://user-images.githubusercontent.com/14800198/234110362-967b9008-ab5b-413b-ba31-8dbf543a5165.png)
![image](https://user-images.githubusercontent.com/14800198/234110473-eb07ac40-ff91-4116-8272-b97a103dff7e.png)
![image](https://user-images.githubusercontent.com/14800198/234110274-c28aca28-4110-4c1a-9520-8d1703f09620.png)

2023-04-24 20:39 UTC, vapopescu commented on apps/frontend/src/app/Data/Weapons/WeaponSheet.tsx
>    }
There may be a more efficient way to write this, but I'm not that good with TypeScript

2023-04-24 20:40 UTC, vapopescu commented on libs/dm-localization/src/lib/parseUtil.ts
> +const paragraph2 = (string: string) => {
Function name may be changed. I was lazy :)

2023-04-25 23:24 UTC, nguyentvan7 approved these changes

2023-04-28 08:42 UTC, frzyc commented
I think the proper fix is to amend the original `paragraph` function:
```
const parsed = string.split('\\n').map((s) => s || '<br/>')
```
to
```
const parsed = string.split(/\\{1,2}n/gm).map((s) => s || '<br/>')
```

2023-04-28 08:48 UTC, frzyc requested changes
I think the proper fix is to amend the original paragraph function:
```
const parsed = string.split('\\n').map((s) => s || '<br/>')
```
to
```
const parsed = string.split(/\\{1,2}n/gm).map((s) => s || '<br/>')
```

2023-04-29 18:39 UTC, vapopescu commented
@frzyc Sorry for being a newb,. It seems thats, React is happy to receive an array as well as strings, so the original `paragraph` filter already worked as-is. It just needed to be used here. As a side-effect, weapon descriptions are now arrays, and weapon passive descriptions are 2D-arrays. E.g. Favonius codex

```
{
  "name": "Favonius Codex",
  "description": {
    "0": "A secret tome that belonged to the scholars of the Knights of Favonius. It describes the logic and power of elements and matter."
  },
  "passiveName": "Windfall",
  "passiveDescription": {
    "0": {
      "0": "CRIT Hits have a <cryo>60%</cryo> chance to generate a small amount of Elemental Particles, which will regenerate 6 Energy for the character. Can only occur once every <cryo>12</cryo>s."
    },
    "1": {
      "0": "CRIT Hits have a <cryo>70%</cryo> chance to generate a small amount of Elemental Particles, which will regenerate 6 Energy for the character. Can only occur once every <cryo>10.5</cryo>s."
    },
    "2": {
      "0": "CRIT Hits have a <cryo>80%</cryo> chance to generate a small amount of Elemental Particles, which will regenerate 6 Energy for the character. Can only occur once every <cryo>9</cryo>s."
    },
    "3": {
      "0": "CRIT Hits have a <cryo>90%</cryo> chance to generate a small amount of Elemental Particles, which will regenerate 6 Energy for the character. Can only occur once every <cryo>7.5</cryo>s."
    },
    "4": {
      "0": "CRIT Hits have a <cryo>100%</cryo> chance to generate a small amount of Elemental Particles, which will regenerate 6 Energy for the character. Can only occur once every <cryo>6</cryo>s."
    }
  }
}
```

2023-05-31 04:04 UTC, frzyc approved these changes

2023-07-01 07:01 UTC, nguyentvan7 approved these changes

2023-07-01 07:01 UTC, merged