Add nightly deployment action
frzyc/genshin-optimizer pull request #1164
Opened 2023-04-25 21:34 UTC by nguyentvan7

* Add a scheduled action to deploy master nightly to a separate URL `https://frzyc.github.io/genshin-optimizer/nightly`
* Also allows deploying manually
* Partially resolves #1060

2023-04-25 21:41 UTC, nguyentvan7 commented
You can see my testing here:
https://github.com/nguyentvan7/genshin-optimizer/actions/runs/4801922351

And you can see that https://nguyentvan7.github.io/genshin-optimizer/#/characters and https://nguyentvan7.github.io/genshin-optimizer/nightly/#/characters coexist together while on different versions

2023-04-27 20:34 UTC, nguyentvan7 commented on .github/workflows/nightly.yml
> +          git commit -m "Nightly build"
Fails if there have been no changes since last nightly

2023-04-27 20:34 UTC, nguyentvan7 commented on .github/workflows/nightly.yml
> +          NX_URL_GITHUB_GO_CURRENT_VERSION="https://github.com/${{ github.repository }}/commit/$(git rev-parse HEAD)" \
Maybe consider changing the package.json version to have the current date postpended as well, to indicate its a nightly

2023-04-27 21:16 UTC, eeeqeee requested changes

2023-04-28 04:59 UTC, nguyentvan7 commented on .github/workflows/nightly.yml
> +    - cron: '8 20 * * *' # Midnight-ish NA time. Offset from the hour to hopefully avoid job delays
Makes it less of a nightly and more of a bleeding edge canary I suppose. @frzyc thoughts? Idk if he even wants a nightly anyways

2023-04-28 05:10 UTC, eeeqeee commented on .github/workflows/nightly.yml
> +    - cron: '8 20 * * *' # Midnight-ish NA time. Offset from the hour to hopefully avoid job delays
We already have https://eeeqeee.github.io/genshin-optimizer-nightly/frzyc/master/ for daily builds of `master`

2023-04-28 17:44 UTC, nguyentvan7 commented on .github/workflows/nightly.yml
> +    - cron: '8 20 * * *' # Midnight-ish NA time. Offset from the hour to hopefully avoid job delays
Should we just migrate your action to this repo then?

2023-04-29 01:36 UTC, eeeqeee commented on .github/workflows/nightly.yml
> +    - cron: '8 20 * * *' # Midnight-ish NA time. Offset from the hour to hopefully avoid job delays
We could, but keeping it outside means that we avoid a potential db bug from affecting users' live data

2023-04-29 05:16 UTC, nguyentvan7 commented
Closing since eeeqeee has a nightly already set up

2023-04-29 05:16 UTC, closed without merging