Add dev-only UI configuration
frzyc/genshin-optimizer pull request #1311
Opened 2023-10-21 20:20 UTC by nguyentvan7

## Describe your changes

Added a util function to be used for dev-only components, such as ones in development, but that still want to be merged in an off-state.

These components will only show in a local dev environment, or on deployments with the flag set.

Updated PR deployment actions to check the labels. If `showDevComponents` is present, it will deploy the site with dev-only components visible, ideal for testing.

Added a small indicator to the app header when dev components are shown.

PRs will now redeploy when labels are changed.

## Issue or discord link

N/A

## Testing/validation

Picture of the dev indicator:
![image](https://github.com/frzyc/genshin-optimizer/assets/36019388/de2abb35-376b-44f6-b57b-521c738fbcdd)

## Checklist before requesting a review (leave this PR as draft if any part of this list is not done.)

- [ ] I have commented my code, in hard-to understand areas.
- [ ] I have made corresponding changes to README or wiki.
- [ ] For front-end changes, I have updated the corresponding English translations.
- [ ] Ran `yarn run mini-ci` locally to validate format + lint.
- [ ] If there were format issues, I ran `nx format write` to resolve them automatically.

2023-10-21 20:53 UTC, frzyc submitted a review, later dismissed

2023-10-21 21:04 UTC, frzyc approved these changes

2023-10-29 01:00 UTC, frzyc requested changes
<img width="288" alt="image" src="https://github.com/frzyc/genshin-optimizer/assets/1754901/778489c4-37fb-4fa9-a544-12147a9dcaab">
Does this break `process` under `gi-frontend`?

2023-10-29 01:51 UTC, nguyentvan7 commented
This doesnt change anything in gi-frontend nor how process is handled so that is an existing bug of some sort. This is broken on #1313 as well, so its unrelated to my PR

2023-11-07 23:55 UTC, frzyc approved these changes

2023-11-07 23:55 UTC, merged