Character talent tab translations
frzyc/genshin-optimizer pull request #1359
Opened 2023-12-03 12:23 UTC by liaojh1998

## Describe your changes

* Resolves translation comments in #1358.
* Standardized translations to languages in Genshin by the following:
  * Changes "Normal/Charged Attack" to just "Normal Attack". All translations use "Normal Attack".
  * All "Constellation Lv." follows the same translations as Genshin.
  * All "Talent Lv." follows the same translations as Genshin.
  * Instead of "Unlocked at Ascension #", use the same translations in Genshin for "Unlocks at Character Ascension Phase #".
  * Instead of "Unlocked by Default", modified to "Passive Talent" and used the same Genshin translations for "Passive Talent".

## Testing/validation

![image](https://github.com/frzyc/genshin-optimizer/assets/22307142/e2bda051-f172-4c8c-8e07-6cbaaf8a5a8f)
![image](https://github.com/frzyc/genshin-optimizer/assets/22307142/07e8c6be-baea-476d-83d5-66a69e980617)
![image](https://github.com/frzyc/genshin-optimizer/assets/22307142/6f55f97c-17bc-4a5a-8610-295e27d63547)
![image](https://github.com/frzyc/genshin-optimizer/assets/22307142/16a1cdde-07b2-4182-8f9e-8cc104d37b1d)

## Checklist before requesting a review (leave this PR as draft if any part of this list is not done.)

- [x] I have commented my code, in hard-to understand areas.
- [x] I have made corresponding changes to README or wiki.
- [x] For front-end changes, I have updated the corresponding English translations.
- [x] Ran `yarn run mini-ci` locally to validate format + lint.
- [x] If there were format issues, I ran `nx format write` to resolve them automatically.

2023-12-03 12:28 UTC, liaojh1998 commented
Blocking until #1358 is submitted.

2023-12-03 17:26 UTC, frzyc requested changes
Hey @liaojh1998, I appreciate your work here on the translations. We are currently putting this site on maintenance mode, in favor of working on a new UI with a new calculation engine. so I am generally not scoping time for translations for this UI. However, I want to make sure that your time is respected, and I will work with you to put this translations in, especially since you've spent the time to update the translations.

2023-12-03 17:26 UTC, frzyc commented on libs/gi-localization/assets/locales/en/page_character.json
> +    "constellation_lv": {
You can use https://www.i18next.com/translation-function/interpolation to minimize the churn in `constellationLvl` and in `talentLvl`

2023-12-03 23:08 UTC, liaojh1998 commented
Thanks, I'll hold off on any translation stuff in other changes. Sorry for the inconvenience here.

2023-12-04 03:20 UTC, PolomoPT requested changes
I take it those translations were datamined, yeah? You should have them out of the localizations file, then.

Get the string ID and list it under libs/gi-dm-localization/src/executors/gen-locale/lib/Data/sheet.ts, and then reference that instead. We reference stuff in that file typically with `stg`, you can find it in most character pages.

TL;DR: gi-localization is for things that need manual translation, such as conditionals. these extracted strings should be in gi-dm-localization, including the English ones.

2023-12-29 02:40 UTC, frzyc approved these changes

2023-12-29 05:17 UTC, nguyentvan7 approved these changes
Deployed and tested with onetime deployment pipeline. Will clean after merge

2023-12-29 05:17 UTC, merged