update silly wisher assets to 0.35
frzyc/genshin-optimizer pull request #1488
Opened 2024-02-07 04:58 UTC by furrycatherder

## Describe your changes

Update the Silly Wisher assets to 0.35.

## Issue or discord link

- 

## Testing/validation

## Checklist before requesting a review (leave this PR as draft if any part of this list is not done.)

- [ ] I have commented my code in hard-to understand areas.
- [ ] I have made corresponding changes to README or wiki.
- [ ] For front-end changes, I have updated the corresponding English translations.
- [ ] I have run `yarn run mini-ci` locally to validate format and lint.
- [ ] If I have added a new library or app, I have updated the deployment scripts to ignore changes as needed

2024-02-07 05:01 UTC, nguyentvan7 reviewed
<img width="599" alt="image" src="https://github.com/frzyc/genshin-optimizer/assets/36019388/fc6451e3-8e4d-47a8-b220-926549e712d8">
xianyun looks a lot like gaming

2024-02-07 05:05 UTC, nguyentvan7 approved these changes

2024-02-07 05:06 UTC, furrycatherder commented
Should be good to go now. 🙂

2024-02-07 20:30 UTC, nguyentvan7 submitted a review, later dismissed

2024-02-08 19:07 UTC, frzyc requested changes
Looks like `Xianyun` is mispelled, not sure why this was not being picked up from pipeline.

2024-02-08 19:07 UTC, frzyc commented on libs/gi/silly-wisher/src/portraits/index.ts
> +import Xianyun from './portrait_xiangyun.png'
```suggestion
import Xianyun from './portrait_xianyun.png'
```

2024-02-08 19:07 UTC, frzyc commented on libs/gi/silly-wisher/src/splash/index.ts
> +import Xianyun from './splash_xiangyun.png'
```suggestion
import Xianyun from './splash_xianyun.png'
```

2024-02-08 19:15 UTC, frzyc approved these changes

2024-02-08 22:22 UTC, merged