Feature/max rv filter
frzyc/genshin-optimizer pull request #1517
Opened 2024-02-20 19:18 UTC by HassnHamada

## Describe your changes

I've added a feature to filter by maximum potential RV.
This feature has been implemented in the artifact main pages and involved changes to the following files:

* /apps/frontend/src/app/Components/Artifact/ArtifactFilterDisplay.tsx
* /apps/frontend/src/app/PageArtifact/ArtifactSort.ts
* /libs/gi/db/src/Database/DataEntries/DisplayArtifactEntry.ts

![max-rv-filter-480@10](https://github.com/frzyc/genshin-optimizer/assets/44922829/b4a58a08-5a0c-4dbd-8066-67aa9b4262de)

## Issue or discord link

- 

## Testing/validation

I have run `yarn run mini-ci` locally, and all tests have passed successfully.

![Screenshot_280](https://github.com/frzyc/genshin-optimizer/assets/44922829/1c90d4e2-acb7-4d20-ab50-f3aaa358f3cb)

**But I didn't add any new tests.**

## Checklistbefore requesting a review (leave this PR as draft if any part of this list is not done.)

- [ ] I have commented my code in hard-to understand areas.
- [ ] I have made corresponding changes to README or wiki.
- [ ] For front-end changes, I have updated the corresponding English translations.
- [x] I have run `yarn run mini-ci` locally to validate format and lint.
- [ ] If I have added a new library or app, I have updated the deployment scripts to ignore changes as needed

2024-02-21 00:42 UTC, frzyc requested changes
Hey @HassnHamada , Thanks for your contribution. Can you remove the yarn.lock and yarn cache changes? I am not sure they there is so much file churn here, but you should be able to use the current version of the dependencies.

2024-02-21 02:13 UTC, HassnHamada commented
@frzyc I just reverted the changes it should be good now. [Here](https://github.com/HassnHamada/genshin-optimizer/compare/bfafba6372aca0b65df455785e0805956e76296c...97401e2183c94727e0b2c2ebcdcc8a7d4cd444bb) is a diff between the base and the last commit.

2024-02-21 03:42 UTC, frzyc commented on apps/frontend/src/app/Components/Artifact/RVSlide.tsx
> +        <Button
This behaviour seems kind of complicated, I wonder if it makes sense to just have both RV filters, and remove this `useMaxRV` complexity?

2024-02-21 03:57 UTC, frzyc commented on libs/gi/db/src/Database/DataEntries/DisplayArtifactEntry.ts
> +  mrvLow: number
I think your implementation is flawed from the data perspective, you should have 3 data: `rvLow, rvHigh, useMaxRv`. Currently, the RV values are not persisted when you toggle between `useMaxRv`, and after page refresh, the value of the toggle is not persisted either.

2024-02-21 04:00 UTC, frzyc commented on apps/frontend/src/app/Components/Artifact/RVSlide.tsx
> +            '&:hover': { transform: 'translate(-3px, -3px)' },
I am not sure about the additional hover effect on this button, and the fixed width makes this button seemed cramped. My opinion is that you should split the button/input with a <Divider/>, and add more spacing.

2024-02-21 04:03 UTC, frzyc submitted a review, later dismissed
Some concerns about implementation.

2024-02-22 17:41 UTC, nguyentvan7 reviewed
<img width="54" alt="image" src="https://github.com/frzyc/genshin-optimizer/assets/36019388/761df636-f34f-46e7-ae2c-42424230cac2">
padding kinda funky

2024-02-22 19:14 UTC, HassnHamada commented
I could remove the padding and center the text. But I was trying to stay consistent with the level slider padding.

![Screenshot_281](https://github.com/frzyc/genshin-optimizer/assets/44922829/97c302f4-ca64-43a6-b8af-7488c233a3a1)
![Screenshot_282](https://github.com/frzyc/genshin-optimizer/assets/44922829/224aac84-4f00-4a2b-9a69-ab9ff2f358a2)

Another idea is to do like [this](https://discord.com/channels/785153694478893126/1209509900460228708/1209621217481334805) comment suggests. It is a good idea to not change the UI, but it may be restrictive for users.

I would like to hear your thoughts.

2024-02-22 19:17 UTC, nguyentvan7 commented
I like the first option

2024-02-22 19:18 UTC, frzyc commented
https://genshin-optimizer-prs.github.io/pr/1517/frontend/

2024-02-22 19:30 UTC, frzyc commented
I agree with centering the "RV"/"MRV". I appreciate the consideration you are putting in.

2024-02-22 20:22 UTC, HassnHamada commented
This may also be good change. Just to match them.

![Screenshot_283](https://github.com/frzyc/genshin-optimizer/assets/44922829/2a7bdf43-f423-45e2-9524-cfc575db7a64)
![Screenshot_284](https://github.com/frzyc/genshin-optimizer/assets/44922829/5190502e-d50b-4ea6-9d32-52086a040728)

PS: Do you prefer communicating on GitHub or Discord?

2024-02-22 20:24 UTC, nguyentvan7 commented
Oh yea that looks good

Discord is preferred for initial conversation about the feature. once the code is here, it is up to you. If you think there will be a lot of back and forth, discord is probably easier

2024-02-23 06:32 UTC, nguyentvan7 approved these changes

2024-02-23 06:33 UTC, merged