Remove default team description
frzyc/genshin-optimizer pull request #1746
Opened 2024-03-16 02:51 UTC by nguyentvan7

## Describe your changes

## Issue or discord link

- Resolve #1719 

## Testing/validation

## Checklist before requesting a review (leave this PR as draft if any part of this list is not done.)

- [ ] I have commented my code in hard-to understand areas.
- [ ] I have made corresponding changes to README or wiki.
- [ ] For front-end changes, I have updated the corresponding English translations.
- [ ] I have run `yarn run mini-ci` locally to validate format and lint.
- [ ] If I have added a new library or app, I have updated the deployment scripts to ignore changes as needed

2024-03-16 04:38 UTC, frzyc requested changes
Same needs to be applied to loadouts(TeamChar) and builds (both Build and BuildTc) to close out #1719

2024-03-19 23:34 UTC, frzyc requested changes
Looks like loadout changes caused a conflict. the name/desc component was moved to https://github.com/frzyc/genshin-optimizer/blob/master/apps/frontend/src/app/Components/Team/Loadout/LoadoutNameDesc.tsx.

2024-03-20 02:48 UTC, frzyc approved these changes

2024-03-20 02:59 UTC, Jomata approved these changes

2024-03-20 03:00 UTC, merged