Add names char limit
frzyc/genshin-optimizer pull request #1754
Opened 2024-03-16 05:54 UTC by nhanaa

## Describe your changes

- Added truncate string util function to truncate string if over certain length
- Added limits to names and placeholders to indicate the limits
- Truncate the names displayed

## Issue or discord link

- From suggestions in #1648 

## Testing/validation

![image](https://github.com/frzyc/genshin-optimizer/assets/22243393/0ce5400c-b67e-48b3-ad1e-5eee5ce40cd7)
![image](https://github.com/frzyc/genshin-optimizer/assets/22243393/e4fd229d-f10d-43e9-9034-fcbac4902922)
![image](https://github.com/frzyc/genshin-optimizer/assets/22243393/7db9ac2e-8e54-4bbd-8b2e-224d824d5fc3)
![image](https://github.com/frzyc/genshin-optimizer/assets/22243393/1b51a615-06c0-45fe-8316-61eada9bb8c9)

## Checklist before requesting a review (leave this PR as draft if any part of this list is not done.)

- [ ] I have commented my code in hard-to understand areas.
- [ ] I have made corresponding changes to README or wiki.
- [ ] For front-end changes, I have updated the corresponding English translations.
- [ ] I have run `yarn run mini-ci` locally to validate format and lint.
- [ ] If I have added a new library or app, I have updated the deployment scripts to ignore changes as needed

2024-03-16 06:54 UTC, frzyc requested changes
I think more truncation may be needed for team and loadout names:

In format of ( display / truncate) 
 - team ( 100 / 200)
 - loadout ( 100 / 200)
 - Build (50 /100)
 
For truncating the string(enforce final length), I'd recommend doing it in the database.
Since all data is validated in the database, ensuring string length should be as well:
[code that validates loadout(TeamChar) name string](https://github.com/frzyc/genshin-optimizer/blob/master/libs/gi/db/src/Database/DataManagers/TeamCharacterDataManager.ts#L103)

2024-03-16 06:54 UTC, frzyc commented on libs/common/util/src/lib/string.ts
> +  return str.length > length ? str.slice(0, length) + '...' : str
```suggestion
  return str.length > length ? str.slice(0, length) + '...' : str
  return str.length > length ? str.slice(0, length-3) + '...' : str
```

2024-03-17 05:32 UTC, nhanaa commented
> I think more truncation may be needed for team and loadout names:
> 
> In format of ( display / truncate)
> 
> * team ( 100 / 200)
> * loadout ( 100 / 200)
> * Build (50 /100)
> 
> For truncating the string(enforce final length), I'd recommend doing it in the database. Since all data is validated in the database, ensuring string length should be as well: [code that validates loadout(TeamChar) name string](https://github.com/frzyc/genshin-optimizer/blob/master/libs/gi/db/src/Database/DataManagers/TeamCharacterDataManager.ts#L103)

By doing it in the database, do you mean truncating the string before saving the names in the database?

2024-03-17 07:12 UTC, frzyc commented
> > I think more truncation may be needed for team and loadout names:
> > In format of ( display / truncate)
> > 
> > * team ( 100 / 200)
> > * loadout ( 100 / 200)
> > * Build (50 /100)
> > 
> > For truncating the string(enforce final length), I'd recommend doing it in the database. Since all data is validated in the database, ensuring string length should be as well: [code that validates loadout(TeamChar) name string](https://github.com/frzyc/genshin-optimizer/blob/master/libs/gi/db/src/Database/DataManagers/TeamCharacterDataManager.ts#L103)
> 
> By doing it in the database, do you mean truncating the string before saving the names in the database?

I guess is should be more specific since your function is called `truncateString`. Slicing the string down to max size, should happen on the database size, before the `name` is saved. Applying the ellipsis, should be done on the UI(and does not change the database string size).

2025-01-25 18:40 UTC, nguyentvan7 commented
Stale

2025-01-25 18:40 UTC, closed without merging