fix team page routing
frzyc/genshin-optimizer pull request #1913
Opened 2024-04-08 09:53 UTC by frzyc

## Describe your changes

Current implementation is missing a layer in routing, which made all end route logic more complicated. 
This PR addes that extra layer in routing, and simplifies that logic.

## Issue or discord link

- 

## Testing/validation

## Checklist before requesting a review (leave this PR as draft if any part of this list is not done.)

- [ ] I have commented my code in hard-to understand areas.
- [ ] I have made corresponding changes to README or wiki.
- [ ] For front-end changes, I have updated the corresponding English translations.
- [ ] I have run `yarn run mini-ci` locally to validate format and lint.
- [ ] If I have added a new library or app, I have updated the deployment scripts to ignore changes as needed

2024-04-08 23:46 UTC, nguyentvan7 requested changes
Open a team
click team settings
swap the character you are on for a different character
the page will update for the new character, but the URL will still be the old character

2024-04-09 00:07 UTC, frzyc commented
Looks like there is a flaw with the new-team workflow routing. This might need further time to cook.

2024-04-09 07:02 UTC, nguyentvan7 commented
Will this fix the following?
* #1904 
* #1905

2024-04-09 15:28 UTC, nguyentvan7 approved these changes

2024-04-09 15:29 UTC, merged