Tallies added for teams and loadouts
frzyc/genshin-optimizer pull request #2070
Opened 2024-05-05 02:45 UTC by maoadrian12

## Describe your changes

Added a tally when looking at databases for the number of teams and loadouts.

## Issue or discord link

https://github.com/frzyc/genshin-optimizer/issues/2040

## Testing/validation

BEFORE
![image](https://github.com/frzyc/genshin-optimizer/assets/111794367/b2fcfdf2-3082-4c54-bd9e-1bb2a2858530)
AFTER
![image](https://github.com/frzyc/genshin-optimizer/assets/111794367/2df8ddf4-0413-4692-a20c-c439ee3ae648)

## Checklist before requesting a review (leave this PR as draft if any part of this list is not done.)

- [ x ] I have commented my code in hard-to understand areas.
- [  ] I have made corresponding changes to README or wiki.
- [  ] For front-end changes, I have updated the corresponding English translations.
- [ x ] I have run `yarn run mini-ci` locally to validate format and lint.
- [ x ] If I have added a new library or app, I have updated the deployment scripts to ignore changes as needed

2024-05-05 02:53 UTC, frzyc requested changes
<img width="476" alt="image" src="https://github.com/frzyc/genshin-optimizer/assets/1754901/07cd6ba4-d110-45db-ad2f-1c249bb97850">
Is it possible to move the last edit time here?, Will balance out the whitespace.
Also, update translations in https://github.com/frzyc/genshin-optimizer/blob/master/libs/gi/localization/assets/locales/en/settings.json

2024-05-05 16:37 UTC, maoadrian12 commented
Looks like this now:
![image](https://github.com/frzyc/genshin-optimizer/assets/111794367/f0d6be3a-f5b2-4237-ad4a-4493ceb91122)
Not sure if this is intended behavior or not, but when the loadouts are changed/updated, it doesn't change the lastEdit time listed under the database.

2024-05-05 16:57 UTC, frzyc commented
> Looks like this now: ![image](https://private-user-images.githubusercontent.com/111794367/328033405-f0d6be3a-f5b2-4237-ad4a-4493ceb91122.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5Mjg1NDcsIm5iZiI6MTcxNDkyODI0NywicGF0aCI6Ii8xMTE3OTQzNjcvMzI4MDMzNDA1LWYwZDZiZTNhLWY1YjItNDIzNy1hZDRhLTQ0OTNjZWI5MTEyMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNVQxNjU3MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MDRhYWE0MzgzNDRmNGFjZjVjZTQzNzc1Njk2M2EzYThjMGU4M2Q5ZTZlODA0MzYxMWEzODI1ZTZlZjZhNzYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.M7-jtk2KGT5NdhY8kw6BAChxJuBQMzUJtPZTh--bWL8) Not sure if this is intended behavior or not, but when the loadouts are changed/updated, it doesn't change the lastEdit time listed under the database.

Looks much better now. That is a good catch on the `lastEdit` issue: https://github.com/frzyc/genshin-optimizer/issues/2072

2024-05-05 16:58 UTC, frzyc requested changes
Need to pass format CI stage:
assuming you are running a fork with upstream set to the main repo, you can run `nx format write --base upstream/master`

2024-05-05 17:05 UTC, frzyc requested changes

2024-05-05 17:05 UTC, frzyc commented on libs/gi/ui/src/components/database/DatabaseCard.tsx
> +  let numLoadouts = 0;
The number of loadouts should just be `database.teamChars.values.length`. 

Can you also include the number of builds?
`database.builds.values.length`

2024-05-05 19:11 UTC, maoadrian12 commented
> Need to pass format CI stage: assuming you are running a fork with upstream set to the main repo, you can run `nx format write --base upstream/master`. Next time, it might be better to create a feature branch in your fork to avoid this issue.

How should I know if the formatting is correct, when I run the command(yarn run nx format:check) I get a lot of CRLF warnings, is that fine?
Besides that, here's what the screen looks like now:
![image](https://github.com/frzyc/genshin-optimizer/assets/111794367/e9fec3db-793b-4fd1-9035-d0cb24a0d64b)

2024-05-05 19:19 UTC, frzyc commented
> I get a lot of CRLF warnings, is that fine?

I think you need to change your autocrlf settings in git:
```
git config core.autocrlf false
```

2024-05-05 20:25 UTC, maoadrian12 commented
When I do yarn run mini-ci, I only fail the gi-dm-localization test because the file at libs/gi/dm/GenshinData/TextMap/TextMapCHS.json isn't found, is this fine?

2024-05-05 20:56 UTC, frzyc commented
That missing file is likely due to the datamine submodule not being loaded, you can run `reload-dm` for that. For the format issue, you can follow the instructions here https://github.com/frzyc/genshin-optimizer/pull/2070#pullrequestreview-2039740685. (mini-ci is suppose to run format, but it won't work for you here because you are working off your fork's master)

2024-05-06 16:36 UTC, maoadrian12 commented
Did I break something? The checks have been going on for a while

2024-05-06 16:42 UTC, frzyc commented
> Did I break something? The checks have been going on for a while

Nope, because you are a first contributor, the pipeline needs approval before running. I've started it.

2024-05-06 16:51 UTC, frzyc approved these changes

2024-05-06 16:52 UTC, frzyc commented
LGTM, thanks for your work!.

2024-05-06 16:52 UTC, merged