Allow to edit loadout name via clicking on loadout name
frzyc/genshin-optimizer pull request #2215
Opened 2024-06-06 23:55 UTC by bluezettabyte

## Describe your changes

Allow users to click on loadout name to edit loadout name/description

## Issue or discord link

Resolve #2135 

## Testing/validation

![image](https://github.com/frzyc/genshin-optimizer/assets/37258523/bd2ff988-5c92-45dd-81ec-c8e6c8a280df)

## Checklist before requesting a review (leave this PR as draft if any part of this list is not done.)

- [ ] I have commented my code in hard-to understand areas.
- [ ] I have made corresponding changes to README or wiki.
- [ ] For front-end changes, I have updated the corresponding English translations.
- [x] I have run `yarn run mini-ci` locally to validate format and lint.
- [ ] If I have added a new library or app, I have updated the deployment scripts to ignore changes as needed

2024-06-07 04:07 UTC, frzyc requested changes
LGTM, just need to pass format/lint.

2024-06-07 04:07 UTC, frzyc commented on libs/gi/page-team/src/CharacterDisplay/Content.tsx
> +                      onChange={(loadoutName) => handleName(loadoutName)}
more of a nit, can be simplified
```suggestion
                      onChange={handleName}
```

2024-06-07 16:11 UTC, nguyentvan7 requested changes
Padding fix as well, sorry for iterations

2024-06-07 16:11 UTC, nguyentvan7 commented on libs/gi/page-team/src/CharacterDisplay/Content.tsx
>              position: 'relative',
Change the `pb` above to `p`

2024-06-07 16:11 UTC, nguyentvan7 commented on libs/gi/page-team/src/CharacterDisplay/Content.tsx
> +          <CardActionArea onClick={() => setEditMode(true)}>
add `sx={{ p: 2 }}`

2024-06-07 16:12 UTC, nguyentvan7 commented
Also format failed

2024-06-08 14:49 UTC, frzyc approved these changes
LGTM

2024-06-08 15:04 UTC, merged