Bold the selected header tab text second attempt without affecting wi…
frzyc/genshin-optimizer pull request #2279
Opened 2024-06-28 12:55 UTC by claireoe

Bold the selected header tab text second attempt without affecting width of header tab

**Issue:**
 Bold the selected header tab text #2263

**Changes:** 
Updated the theme with text shadow to bold selected header tab text.

Validation
<img width="938" alt="home bold" src="https://github.com/frzyc/genshin-optimizer/assets/142216709/76ff211f-6e85-46c8-be40-2a953d1eac5a">
 Dimensions before and after bold applied: 307.39 x48

2024-06-28 18:46 UTC, nguyentvan7 commented
![image](https://github.com/frzyc/genshin-optimizer/assets/36019388/2a6fb46d-c853-4b1d-837e-e25613d3cc2b)
This doesnt really look right

2024-06-29 05:01 UTC, frzyc requested changes
Yeah, I tried this solution before, and I am not too keen on it, since it makes the font sort of "rounded" but I guess this is probably the easiest way to do this. 

Lets iterate on this solution:
- decrease the spread of the textshadow a little, maybe to 0.25px? see if that makes the font less rounded when "bolded"?
- Make the main Tab "Genshin Optimizer" not bolded by default so it does not get double bolded
- Apply the same bolding to the hamburger menu items in mobile view.
- FInally, to pass the format CI, run `yarn run mini-ci`

2024-07-02 11:24 UTC, frzyc requested changes
This iteration looks good enough to me. 
Just need to pass format CI, please run `nx format:write`.

2024-07-02 11:24 UTC, frzyc commented on apps/frontend/src/app/Header.tsx
> +                // fontWeight: 'Bold',
remove

2024-07-02 11:24 UTC, frzyc commented on apps/frontend/src/app/Header.tsx
> +
remove extra line

2024-07-02 11:24 UTC, frzyc commented on apps/frontend/src/app/Header.tsx
> +                <Typography >
extra space (which is probably failing the format CI)

2024-07-03 12:39 UTC, frzyc approved these changes
Thanks for iterating on this solution with me. I appreciate the contribution.

2024-07-03 12:39 UTC, merged

2024-07-04 13:27 UTC, claireoe commented
@frzyc thanks for the opportunity, enjoyed working on it.