Teamcard glowup
frzyc/genshin-optimizer pull request #2323
Opened 2024-07-18 01:55 UTC by frzyc

## Describe your changes

Making some changes according to figma
<img width="1547" alt="image" src="https://github.com/user-attachments/assets/2766fb5c-1c72-48bf-95f9-0a93c6e60a2b">

## Issue or discord link

- 

## Testing/validation

## Checklist before requesting a review (leave this PR as draft if any part of this list is not done.)

- [ ] I have commented my code in hard-to understand areas.
- [ ] I have made corresponding changes to README or wiki.
- [ ] For front-end changes, I have updated the corresponding English translations.
- [ ] I have run `yarn run mini-ci` locally to validate format and lint.
- [ ] If I have added a new library or app, I have updated the deployment scripts to ignore changes as needed

2024-07-18 05:10 UTC, nguyentvan7 requested changes

2024-07-18 05:10 UTC, nguyentvan7 commented on libs/common/ui/src/components/Card/CardThemed.tsx
>        ? theme.palette.contentLight.main
could you make this a separate function with if else/switch case and return statements? nested  nested nested ternary is impossible to read

2024-07-18 05:10 UTC, nguyentvan7 commented on libs/gi/ui/src/components/team/TeamCard.tsx
> +                  <SandsIcon sx={{ fontSize: 'inherit' }} />
I hovered over this and crashed

Please enter the steps to reproduce this error below:
1. 

**Don't forget to upload your JSON file!**

```
Message: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
Name: Error
Stack: Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at du (https://genshin-optimizer-prs.github.io/pr/2323/frontend/assets/index-C6KbjYFe.js:48:33862)
    at efe (https://genshin-optimizer-prs.github.io/pr/2323/frontend/assets/index-C6KbjYFe.js:46:22379)
    at https://genshin-optimizer-prs.github.io/pr/2323/frontend/assets/index-C6KbjYFe.js:131:23586
    at Ty (https://genshin-optimizer-prs.github.io/pr/2323/frontend/assets/index-C6KbjYFe.js:48:24296)
    at Yx (https://genshin-optimizer-prs.github.io/pr/2323/frontend/assets/index-C6KbjYFe.js:48:31641)
    at IV (https://genshin-optimizer-prs.github.io/pr/2323/frontend/assets/index-C6KbjYFe.js:48:31497)
    at IV (https://genshin-optimizer-prs.github.io/pr/2323/frontend/assets/index-C6KbjYFe.js:48:31405)
    at IV (https://genshin-optimizer-prs.github.io/pr/2323/frontend/assets/index-C6KbjYFe.js:48:31405)
    at IV (https://genshin-optimizer-prs.github.io/pr/2323/frontend/assets/index-C6KbjYFe.js:48:31405)
    at IV (https://genshin-optimizer-prs.github.io/pr/2323/frontend/assets/index-C6KbjYFe.js:48:31405)
```

2024-07-19 05:07 UTC, nguyentvan7 requested changes
![Screenshot_20240718_220615_Chrome](https://github.com/user-attachments/assets/c7614620-b206-4067-9df1-9d438990e8ff)

Hover always says "sands"? (This is a circlet)

2024-07-19 05:31 UTC, frzyc commented
Good catch.

2024-07-19 05:40 UTC, nguyentvan7 approved these changes

2024-07-19 07:37 UTC, merged