Somnia bot i18n translation
frzyc/genshin-optimizer pull request #2335
Opened 2024-07-24 03:14 UTC by Godlander

## Describe your changes

use i18n translations for ability descriptions

## Issue or discord link

## Testing/validation

![image](https://github.com/user-attachments/assets/f9b8693f-d04e-4e94-8fd5-73a9d75d3746)

## Checklist before requesting a review (leave this PR as draft if any part of this list is not done.)

- [ ] I have commented my code in hard-to understand areas.
- [ ] I have made corresponding changes to README or wiki.
- [ ] For front-end changes, I have updated the corresponding English translations.
- [ ] I have run `yarn run mini-ci` locally to validate format and lint.
- [ ] If I have added a new library or app, I have updated the deployment scripts to ignore changes as needed

2024-07-24 23:30 UTC, nguyentvan7 commented on apps/somnia/src/commands/archive.ts
> +    return artifactArchive(id as ArtifactSetKey, lang)
missing await

2024-07-24 23:31 UTC, nguyentvan7 commented on apps/somnia/src/commands/archive/weapon.ts
> +  const mainstat =
Why not use Pando? Could be a future TODO as well i suppose, once we have more of the UI sheets and sheets done

2024-07-25 03:55 UTC, Godlander commented
how the heck did i do that

2024-07-26 06:14 UTC, nguyentvan7 commented on apps/somnia/src/commands/archive/weapon.ts
> +      '\n\n**' +
prob should refactor this and the other text+= into a readable function
`text += passiveNameAndDesc()` for example

2024-07-26 06:16 UTC, nguyentvan7 requested changes
Undo the change to numDisplay, the other 2 comments can be for next PR

2024-07-26 23:09 UTC, nguyentvan7 approved these changes

2024-07-26 23:09 UTC, merged