Update database handling when switching between different databases
frzyc/genshin-optimizer pull request #665
Opened 2022-10-02 06:31 UTC by frzyc

- Allow databases to switch their storage, while maintaining their cached data.
- Database swapping no long have expensive new database initialization steps, since they are swapped "hot".
- Use the data entry classes in database to set/unset data in storage, thus extra data in the localstorage are no longer being bundled in the data of other databases.

2022-10-07 08:14 UTC, nguyentvan7 requested changes

2022-10-07 08:14 UTC, nguyentvan7 commented on src/App.tsx
> +      const db = new ArtCharDatabase(new SandboxStorage(dbObj))
Missing import for SandboxStorage

2022-10-07 08:14 UTC, nguyentvan7 commented on src/PageSettings/DatabaseCard.tsx
> +  }, [setDatabase, mainDB, database])
Missing dependency on `current`

2022-10-07 08:14 UTC, nguyentvan7 commented on src/PageSettings/UploadCard.tsx
> +  }, [database, importedDatabase, reset, setDatabases])
Missing dependency on `databases` and `index`

2022-10-07 20:38 UTC, lantua commented on src/Database/migrate.ts
> +        if (!character) continue
Should already exist from `key` being in `storage.keys`, use `storage.get(key)!`.

2022-10-10 20:57 UTC, nguyentvan7 commented
1. Upload an existing database
2. Swap to it
3. Delete it
4. Upload another database
5. You now have no database selected visually on the screen

2022-10-14 04:34 UTC, nguyentvan7 commented
swap button is completely broken on my end now. doesnt do anything

2022-10-14 14:08 UTC, frzyc commented
@nguyentvan7 database swapping is working fine on my end. Can you double check?

2022-10-14 18:47 UTC, nguyentvan7 commented
Database numbers appear to be 0-indexed now. They are 1-indexed on prod

2022-10-14 19:40 UTC, nguyentvan7 approved these changes

2022-10-14 22:02 UTC, merged