Resolve #637 - Allow artifacts in build results to be edited.
frzyc/genshin-optimizer pull request #668
Opened 2022-10-02 17:25 UTC by frzyc

2022-10-02 19:09 UTC, nguyentvan7 commented
Should we disable editing the set? I edited the feather to be archaic petra, and now the optimization still says eosf 4p, and the burst still has the 4p bonus
<img width="776" alt="image" src="https://user-images.githubusercontent.com/36019388/193471785-cd605f2f-0a15-4169-b74b-51204aea7c6c.png">

2022-10-02 19:09 UTC, nguyentvan7 requested changes
When I edit an artifact, the build stats don't update. Is that intended? (somewhat related to my previous comment I guess?)

2022-10-03 04:09 UTC, frzyc commented
yeah, there are a ton of weird interactions here. I need to look at the update chain for some of these stuff, because the build results UI need to register listener for everything that can change

2022-10-04 04:59 UTC, nguyentvan7 approved these changes

2022-10-04 05:33 UTC, merged