Solver pr
frzyc/genshin-optimizer pull request #947
Opened 2023-02-05 18:31 UTC by tooflesswulf

Created a generalized SolverBase class to pull optimization code out of TabOptimize/index as much as possible.

Without #921 this time.

Functionality should be identical to live.

2023-02-05 19:19 UTC, lantua commented on apps/frontend/src/app/PageCharacter/CharacterDisplay/Tabs/TabOptimize/index.tsx
> +    // END Solver
If it's this short, we probably don't need bracketing comments.

2023-02-05 19:19 UTC, lantua commented on apps/frontend/src/app/Solver/SolverBase.ts
> +      this.cancelled?.then(() => worker.terminate())
`cancelled` is no longer optional

2023-02-05 20:19 UTC, lantua approved these changes

2023-02-05 20:29 UTC, nguyentvan7 approved these changes

2023-02-05 20:42 UTC, tooflesswulf commented
This fixes (https://github.com/frzyc/genshin-optimizer/issues/945) as well

2023-02-06 04:52 UTC, frzyc requested changes
Looks like you removed the windows cached version of esbuild, and commit in install-state.gz
clean up using 
`git checkout 7c1fd65cb9b060ebaf4b6361f02ba7d11c80f013 -- ".yarn/cache/@esbuild-win32-x64-npm-0.16.16-b88e3d7e7d-8.zip" `
and
`git checkout 7c1fd65cb9b060ebaf4b6361f02ba7d11c80f013 -- ".yarn/install-state.gz"`

2023-02-06 04:57 UTC, tooflesswulf commented
OK did the checkout

2023-02-06 05:15 UTC, frzyc approved these changes

2023-02-06 05:30 UTC, merged