Fix database issues.
frzyc/genshin-optimizer pull request #972
Opened 2023-02-11 21:43 UTC by frzyc

2023-02-13 05:38 UTC, nguyentvan7 commented on apps/frontend/src/app/Database/DataManagers/ArtifactData.ts
> +        else if (upgraded[0]) result.artifacts.upgraded.push(art)
Based on if-condition on line 100, one of lines 104 or 105 is guaranteed to run, so we can simplify this

2023-02-13 06:05 UTC, nguyentvan7 requested changes
#405 is not resolved, since there is no additional text explaining why the items are marked as invalid

2023-02-13 09:48 UTC, frzyc commented
> #405 is not resolved, since there is no additional text explaining why the items are marked as invalid

I'm not adding like dozens of text for somewhat self-explainable invalidations, and then getting translators to translate them. Not worth our time imo.

2023-02-14 00:11 UTC, nguyentvan7 commented
Ok then I'll remove #405 and close it separately

2023-02-14 00:11 UTC, nguyentvan7 approved these changes

2023-02-14 00:13 UTC, nguyentvan7 commented
Oh I see why 405 was there. Issue title is misleading since it's 2 issues in 1. I'll still close separately

2023-02-14 00:30 UTC, merged